version: 2

jobs:
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt install -y build-essential cmake make python3
      - run:
          no_output_timeout: 3m
          command: |
            cd tests
            bash tests.sh

workflows:
  version: 2
  test:
    jobs:
      - test